### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by wddzyjhi** [MikroElektronika/Spectral_click#1]
I want to ask
why i used COM(rs232) to connect this borad, and sent "AT" command, it had nothing respond.And the TX pin is always at HIGH level.How can I use this borad to read the color?

**Comment by mvidoje** [comment]
CIE 1931 uses serial communication that's why you have to use it. You can use our ready to use examples with mikroE IDE - there are also tools integrated inside mikroE IDE which can help you to get it work with just few mouse clicks. https://libstock.mikroe.com/projects/view/2348/spectral-click
